eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false  # eureka server自我保护，客户端停止后服务还存在，开发环境、生产环境打开
  instance:
      status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html
      hostname: localhost
spring:
  application:
    name: eureka
#security:
#  basic:
#    enabled: true
#  user:
#    name: admin
#    password: admin
server:
  port: 8761

